/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tesji.vistasCategorias;

import com.tesji.modelo.Categoria;
import com.tesji.vistaPrincipal.FrmPrincipal;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Mitzi_Torales
 */
public class FrmAltaCategoria extends javax.swing.JFrame {

    /**
     * Creates new form FrmAltaCategoria
     */
    public FrmAltaCategoria() {
        initComponents();
        iniciar();
        inhabilitar();
    }
      private void iniciar(){
         setLocationRelativeTo(null);
         setIconImage(Toolkit.getDefaultToolkit().getImage(
                FrmPrincipal.class.getResource(
                        "/com/tesji/imagenes/logotesji.png")));
    }
      
    private void inhabilitar(){
        txtCategoria.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnRegresar.setEnabled(true);
        txtCategoria.setText(null);
    }
    private void habilitar(){
        txtCategoria.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnRegresar.setEnabled(false);
        txtCategoria.requestFocus();
    }
    private void altaCategoria(){
        //Extraer Datos
        String categoria = txtCategoria.getText();
        //Validar campos vacios
        if(categoria.trim().length()==0){
            JOptionPane.showMessageDialog(rootPane, "El campo categoría no debe"
                    + "estar vacio\nIntente de nuevo",
                    "Alta categoría",JOptionPane.ERROR_MESSAGE);
            txtCategoria.requestFocus();
        }else {
            //objeto de tipo categoria            
            Categoria cat = new Categoria();
            if(cat.alta(categoria)){
                JOptionPane.showMessageDialog(rootPane, "Categoría registrada correctamente");
                inhabilitar();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Problemas al registrar "
                        + "categorias\nIntente de nuevo");
            }            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        txtCategoria = new org.edisoncor.gui.textField.TextField();
        btnNuevo = new org.edisoncor.gui.button.ButtonPopup();
        btnCancelar = new org.edisoncor.gui.button.ButtonPopup();
        btnGuardar = new org.edisoncor.gui.button.ButtonNice();
        btnRegresar = new org.edisoncor.gui.button.ButtonIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelNice1.setBackground(new java.awt.Color(204, 0, 153));
        panelNice1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelNice1.setForeground(new java.awt.Color(204, 0, 102));
        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panelNice1.add(panelCurves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        labelTask1.setForeground(new java.awt.Color(255, 255, 255));
        labelTask1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tesji/imagenes/008-doc_edit.gif"))); // NOI18N
        labelTask1.setText(".:: ALTA CATEGORIA ::.");
        labelTask1.setDescription("SISTBOOK");
        panelNice1.add(labelTask1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 20, 280, -1));
        labelTask1.getAccessibleContext().setAccessibleDescription("");

        labelMetric1.setText("Categoría");
        labelMetric1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        panelNice1.add(labelMetric1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 20));
        panelNice1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, -1));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelNice1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelNice1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(102, 204, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelNice1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 40));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tesji/imagenes/back_32x32-32.gif"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelNice1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 47, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        altaCategoria();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        inhabilitar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FrmPrincipal().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAltaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonPopup btnCancelar;
    private org.edisoncor.gui.button.ButtonNice btnGuardar;
    private org.edisoncor.gui.button.ButtonPopup btnNuevo;
    private org.edisoncor.gui.button.ButtonIcon btnRegresar;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.textField.TextField txtCategoria;
    // End of variables declaration//GEN-END:variables
}
