/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tesji.vistasCategorias;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Mitzi_Torales
 */
public class FrmEventoMouse extends javax.swing.JFrame {

    /**
     * Creates new form FrmEventoMouse
     */
    public FrmEventoMouse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTesji = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();
        lblMensaje2 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblFondoVerde = new javax.swing.JLabel();
        lblFondoBlanco = new javax.swing.JLabel();
        lblFondoRosa = new javax.swing.JLabel();
        lblLetra = new javax.swing.JLabel();
        lblLetraRojo = new javax.swing.JLabel();
        lblLetraAmarilla = new javax.swing.JLabel();
        lblLetraAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblTitulo.setText("T E S J I");

        lblMensaje1.setText("X:  , Y:");

        lblMensaje2.setText("X:   , Y:");

        lblFondo.setText("FONDO:");

        lblFondoVerde.setText("VERDE");
        lblFondoVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFondoVerdeMouseEntered(evt);
            }
        });

        lblFondoBlanco.setText("BLANCO");
        lblFondoBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFondoBlancoMouseEntered(evt);
            }
        });

        lblFondoRosa.setText("ROSA");
        lblFondoRosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFondoRosaMouseEntered(evt);
            }
        });

        lblLetra.setText("LETRA:");

        lblLetraRojo.setText("ROJO");
        lblLetraRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLetraRojoMouseEntered(evt);
            }
        });

        lblLetraAmarilla.setText("AMARILLO");
        lblLetraAmarilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLetraAmarillaMouseEntered(evt);
            }
        });

        lblLetraAzul.setText("AZUL");
        lblLetraAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLetraAzulMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlTesjiLayout = new javax.swing.GroupLayout(pnlTesji);
        pnlTesji.setLayout(pnlTesjiLayout);
        pnlTesjiLayout.setHorizontalGroup(
            pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTesjiLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTesjiLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblMensaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(lblMensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTesjiLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFondo)
                    .addComponent(lblLetra))
                .addGap(28, 28, 28)
                .addGroup(pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFondoVerde)
                    .addComponent(lblLetraRojo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFondoBlanco)
                    .addComponent(lblLetraAmarilla))
                .addGap(31, 31, 31)
                .addGroup(pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFondoRosa)
                    .addComponent(lblLetraAzul))
                .addGap(102, 102, 102))
        );
        pnlTesjiLayout.setVerticalGroup(
            pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTesjiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(15, 15, 15)
                .addGroup(pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFondo)
                    .addComponent(lblFondoVerde)
                    .addComponent(lblFondoBlanco)
                    .addComponent(lblFondoRosa))
                .addGap(18, 18, 18)
                .addGroup(pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLetra)
                    .addComponent(lblLetraRojo)
                    .addComponent(lblLetraAmarilla)
                    .addComponent(lblLetraAzul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(pnlTesjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMensaje1)
                    .addComponent(lblMensaje2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTesji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTesji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        lblMensaje1.setText("Click en X: "+ evt.getX()+ " , Y: " + evt.getY());
    }//GEN-LAST:event_formMouseClicked

    private void lblFondoVerdeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoVerdeMouseEntered
        // TODO add your handling code here:
        pnlTesji.setBackground(Color.GREEN);
    }//GEN-LAST:event_lblFondoVerdeMouseEntered

    private void lblLetraRojoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLetraRojoMouseEntered
        // TODO add your handling code here:
        lblTitulo.setForeground(Color.red);
    }//GEN-LAST:event_lblLetraRojoMouseEntered

    private void lblFondoBlancoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoBlancoMouseEntered
        // TODO add your handling code here:
        pnlTesji.setBackground(Color.white);
    }//GEN-LAST:event_lblFondoBlancoMouseEntered

    private void lblFondoRosaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoRosaMouseEntered
        // TODO add your handling code here:
        pnlTesji.setBackground(Color.pink);
    }//GEN-LAST:event_lblFondoRosaMouseEntered

    private void lblLetraAmarillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLetraAmarillaMouseEntered
        // TODO add your handling code here:
        lblTitulo.setForeground(Color.yellow);
    }//GEN-LAST:event_lblLetraAmarillaMouseEntered

    private void lblLetraAzulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLetraAzulMouseEntered
        // TODO add your handling code here:
        lblTitulo.setForeground(Color.blue);
    }//GEN-LAST:event_lblLetraAzulMouseEntered

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        lblMensaje1.setText("Estas presionando el boton del mouse");
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        lblMensaje1.setText("Haz dejado de presionar el boton del mouse");
    }//GEN-LAST:event_formMouseReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        lblMensaje2.setText("X: "+ evt.getX() + " , Y: "+evt.getY());
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEventoMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEventoMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEventoMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEventoMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEventoMouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoBlanco;
    private javax.swing.JLabel lblFondoRosa;
    private javax.swing.JLabel lblFondoVerde;
    private javax.swing.JLabel lblLetra;
    private javax.swing.JLabel lblLetraAmarilla;
    private javax.swing.JLabel lblLetraAzul;
    private javax.swing.JLabel lblLetraRojo;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblMensaje2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlTesji;
    // End of variables declaration//GEN-END:variables
}
